name: Daily Fuel Synthesis on TheCoreNetwork game

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC

jobs:
  random-delay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Your Script
        run: |
          echo "Running the main task"
          PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} python main.py

      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
