name: get_wallet_balances

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 1 AM UTC
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC     

jobs:
  random-delay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dotenv requests

      - name: Run Your Script
        run: |
          echo "Running the main task"
          WALLET_ADDRESS=${{ secrets.WALLET_ADDRESS }} TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }} python balances.py

      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
